#!/usr/bin/env php
<?php
@mkdir('files');
echo '\n🌱 Bienvenido a tu nueva plataforma BISAE\n\n
	  Has dado el primer paso para crear un espacio donde las ideas,\n
      los datos y los sistemas pueden crecer con orden, claridad y propósito.\n\n
      La instalación base se ha completado correctamente.\n\n
      El siguiente paso es dar forma a tu plataforma.\n
      Continúa la instalación visual en tu navegador:\n\n
      👉 http://localhost/plataformaY/installer/install.php\n\n
      Cuando finalices, recuerda eliminar la carpeta /installer por seguridad.\n\n
      Gracias por construir con BISAE.\n
      Felicidades: tu plataforma está a punto de nacer. 🚀✨\n';